spring.application.name=FakeECommerce
spring.datasource.url=jdbc:mysql://localhost:3306/fakeecommerce
spring.datasource.username=root
spring.datasource.password=Vk@#$2211
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create